/*
 * AMD_NPT_family_0Fh_FIDVID_STATUS_register.h
 *
 *  Created on: 12.06.2012
 *      Author: Stefan
 */

#ifndef AMD_NPT_FAMILY_0FH_FIDVID_STATUS_REGISTER_H_
#define AMD_NPT_FAMILY_0FH_FIDVID_STATUS_REGISTER_H_

#define FIDVID_STATUS_MSR_ADDRESS 0xC0010042

// "61 IntPstateSup Intermediate P-state support"
#define INTERMEDIATE_P_STATE_SUPPORT_BIT_ADDRESS 61
// "56 PstateStep P-state Voltage Step"
// "37–32 CurrVID Current VID"
#define CURRENT_VID_START_ADDRESS_IN_BIT 32
// 31 FidVidPending FID/VID Change Pending
// "5–0 CurrFID Current FID"
#define CURRENT_FID_START_BIT 0
#define CURRENT_FID_END_BIT 5
//21–16 MaxFID Max FID
#define MAX_FID_START_ADDRESS_IN_BIT 16

//"53–48 MaxVID Max VID"
#define MAX_VID_START_ADDRESS_IN_BIT 48
#define MAX_VID_START_ADDRESS_IN_BIT_IN_HIGHMOST_BYTES 16

#define MAX_RAMP_VID_START_ADDRESS_IN_BIT 24 // "29–24 MaxRampVID"

#define START_VID_START_ADDRESS_IN_BIT_IN_HIGHMOST_BYTES 8

#endif /* AMD_NPT_FAMILY_0FH_FIDVID_STATUS_REGISTER_H_ */
